INSERT INTO PosORA_Pro.einv_invoice_status (id, name, description, note) VALUES (0, 'Hóa đơn mới tạo', '', '');
INSERT INTO PosORA_Pro.einv_invoice_status (id, name, description, note) VALUES (1, 'Hóa đơn đã cấp số và chờ ký', '', '');
INSERT INTO PosORA_Pro.einv_invoice_status (id, name, description, note) VALUES (2, 'Hóa đơn đã phát hành', '', '');
INSERT INTO PosORA_Pro.einv_invoice_status (id, name, description, note) VALUES (5, 'Hóa đơn điều chỉnh đã cấp số và chờ ký', '', null);
INSERT INTO PosORA_Pro.einv_invoice_status (id, name, description, note) VALUES (6, 'Hóa đơn điều chỉnh đã phát hành', '', null);
INSERT INTO PosORA_Pro.einv_invoice_status (id, name, description, note) VALUES (7, 'Hóa đơn thay thế đã cấp số và chờ ký', '', null);
INSERT INTO PosORA_Pro.einv_invoice_status (id, name, description, note) VALUES (8, 'Hóa đơn thay thế đã phát hành', '', null);
INSERT INTO PosORA_Pro.einv_invoice_status (id, name, description, note) VALUES (9, 'Hóa đơn bị thay thế', '', null);
INSERT INTO PosORA_Pro.einv_invoice_status (id, name, description, note) VALUES (10, 'Hóa đơn bị điều chỉnh', '', null);
INSERT INTO PosORA_Pro.einv_invoice_status (id, name, description, note) VALUES (99, 'Trạng thái khác', '', null);
